server:
  port: 4000
spring:
  application:
    name: hyk-portfolio-back
  servlet:
    multipart:
      max-file-size: 16MB
      max-request-size: 16MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
