spring:
  application:
    name: hyk-portfolio
  data:
    web:
      pageable:
        serialization-mode: via_dto
  mvc:
    problemdetails:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  modulith:
    events:
      jdbc:
        schema-initialization:
          enabled: true
